document.addEventListener('DOMContentLoaded', () => {
    const elements = [
    { symbol: 'H', position: { x: 2, y: 1 }, category: 'red', url: '/pt-table-test/elements_pages/h.html'},
    { symbol: 'He', position: { x: 19, y: 1 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Helio' },
    { symbol: 'Li', position: { x: 2, y: 2 }, category: 'red', url: 'https://es.wikipedia.org/wiki/litio' },
    { symbol: 'Be', position: { x: 3, y: 2 }, category: 'red', url: 'https://es.wikipedia.org/wiki/berilio' },
    { symbol: 'B', position: { x: 14, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/boro' },
    { symbol: 'C', position: { x: 15, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Carbono' },
    { symbol: 'N', position: { x: 16, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/nitrogeno' },
    { symbol: 'O', position: { x: 17, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/oxigeno' },
    { symbol: 'F', position: { x: 18, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Fluor' },
    { symbol: 'Ne', position: { x: 19, y: 2 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Neon' },
    { symbol: 'Na', position: { x: 2, y: 3 }, category: 'red', url: 'https://es.wikipedia.org/wiki/sodio' },
    { symbol: 'Mg', position: { x: 3, y: 3 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Magnesio' },
    { symbol: 'Al', position: { x: 14, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Aluminio' },
    { symbol: 'Si', position: { x: 15, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Silicio' },
    { symbol: 'P', position: { x: 16, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Fosforo' },
    { symbol: 'S', position: { x: 17, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/azufre' },
    { symbol: 'Cl', position: { x: 18, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/cloro' },
    { symbol: 'Ar', position: { x: 19, y: 3 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Argon' },
    { symbol: 'K', position: { x: 2, y: 4 }, category: 'red', url: 'https://es.wikipedia.org/wiki/potasio' },
    { symbol: 'Ca', position: { x: 3, y: 4 }, category: 'red', url: 'https://es.wikipedia.org/wiki/calcio' },
    { symbol: 'Sc', position: { x: 4, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/escandio' },
    { symbol: 'Ti', position: { x: 5, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Titanio' },
    { symbol: 'V', position: { x: 6, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/vanadio' },
    // --------------------------------------------------------------------------------------------------------- 
    { symbol: 'Cr', position: { x: 7, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Krom' },
    { symbol: 'Mn', position: { x: 8, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Mangan' },
    { symbol: 'Fe', position: { x: 9, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Jern' },
    { symbol: 'Co', position: { x: 10, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Kobolt' },
    { symbol: 'Ni', position: { x: 11, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Nikkel' },
    { symbol: 'Cu', position: { x: 12, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Kobber' },
    { symbol: 'Zn', position: { x: 13, y: 4 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Zink' },
    { symbol: 'Ga', position: { x: 14, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Gallium' },
    { symbol: 'Ge', position: { x: 15, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Germanium' },
    { symbol: 'As', position: { x: 16, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Arsen' },
    { symbol: 'Se', position: { x: 17, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Selen' },
    { symbol: 'Br', position: { x: 18, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Brom' },
    { symbol: 'Kr', position: { x: 19, y: 4 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Krypton' },
    { symbol: 'Rb', position: { x: 2, y: 5 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Rubidium' },
    { symbol: 'Sr', position: { x: 3, y: 5 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Strontium' },
    { symbol: 'Y', position: { x: 4, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Yttrium' },
    { symbol: 'Zr', position: { x: 5, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Zirconium' },
    { symbol: 'Nb', position: { x: 6, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Niobium' },
    { symbol: 'Mo', position: { x: 7, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Molybd%C3%A6n' },
    { symbol: 'Tc', position: { x: 8, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Technetium' },
    { symbol: 'Ru', position: { x: 9, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Ruthenium' },
    { symbol: 'Rh', position: { x: 10, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Rhodium' },
    { symbol: 'Pd', position: { x: 11, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Palladium' },
    { symbol: 'Ag', position: { x: 12, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/S%C3%B8lv' },
    { symbol: 'Cd', position: { x: 13, y: 5 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Cadmium' },
    { symbol: 'In', position: { x: 14, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Indium' },
    { symbol: 'Sn', position: { x: 15, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Tin' },
    { symbol: 'Sb', position: { x: 16, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Antimon' },
    { symbol: 'Te', position: { x: 17, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Tellur' },
    { symbol: 'I', position: { x: 18, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Jod' },
    { symbol: 'Xe', position: { x: 19, y: 5 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Xenon' },
    { symbol: 'Cs', position: { x: 2, y: 6 }, category: 'red', url: 'https://es.wikipedia.org/wiki/C%C3%A6sium' },
    { symbol: 'Fr', position: { x: 2, y: 7 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Francium' },
    { symbol: 'Ba', position: { x: 3, y: 6 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Barium' },
    { symbol: 'Ra', position: { x: 3, y: 7 }, category: 'red', url: 'https://es.wikipedia.org/wiki/Radium' },
    { symbol: 'Lu', position: { x: 4, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Lutetium' },
    { symbol: 'Lr', position: { x: 4, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Lawrencium' },  
    { symbol: 'Ce', position: { x: 5, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Cerium' },
    { symbol: 'La', position: { x: 4, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Lanthan' },
    { symbol: 'Ac', position: { x: 4, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Actinium' },
    { symbol: 'Th', position: { x: 5, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Thorium' },
    { symbol: 'Pa', position: { x: 6, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Protactinium' },
    { symbol: 'U', position: { x: 7, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Uran' },
    { symbol: 'Np', position: { x: 8, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Neptunium' },
    { symbol: 'Pu', position: { x: 9, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Plutonium' },
    { symbol: 'Am', position: { x: 10, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Americium' },
    { symbol: 'Cm', position: { x: 11, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Curium' },
    { symbol: 'Bk', position: { x: 12, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Berkelium' },
    { symbol: 'Cf', position: { x: 13, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Californium' },
    { symbol: 'es', position: { x: 14, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Einsteinium' },
    { symbol: 'Fm', position: { x: 15, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Fermium' },
    { symbol: 'Md', position: { x: 16, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Mendelevium' },
    { symbol: 'No', position: { x: 17, y: 10 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Nobelium' },
    { symbol: 'Pr', position: { x: 6, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Praseodym' },
    { symbol: 'Nd', position: { x: 7, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Neodym' },
    { symbol: 'Pm', position: { x: 8, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Promethium' },
    { symbol: 'Sm', position: { x: 9, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Samarium' },
    { symbol: 'Eu', position: { x: 10, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Europium' },
    { symbol: 'Gd', position: { x: 11, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Gadolinium' },
    { symbol: 'Tb', position: { x: 12, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Terbium' },
    { symbol: 'Dy', position: { x: 13, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Dysprosium' },
    { symbol: 'Ho', position: { x: 14, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Holmium' },
    { symbol: 'Er', position: { x: 15, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Erbium' },
    { symbol: 'Tm', position: { x: 16, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Thulium' },
    { symbol: 'Yb', position: { x: 17, y: 9 }, category: 'green', url: 'https://es.wikipedia.org/wiki/Ytterbium' },
    { symbol: 'Hf', position: { x: 5, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Hafnium' },
    { symbol: 'Ta', position: { x: 6, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Tantal' },
    { symbol: 'W', position: { x: 7, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Wolfram' },
    { symbol: 'Re', position: { x: 8, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Rhenium' },
    { symbol: 'Os', position: { x: 9, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Osmium' },
    { symbol: 'Ir', position: { x: 10, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Iridium' },
    { symbol: 'Pt', position: { x: 11, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Platin' },
    { symbol: 'Au', position: { x: 12, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Guld' },
    { symbol: 'Hg', position: { x: 13, y: 6 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Kviks%C3%B8lv' },
    { symbol: 'Tl', position: { x: 14, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Thallium' },
    { symbol: 'Pb', position: { x: 15, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Bly' },
    { symbol: 'Bi', position: { x: 16, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Bismuth' },
    { symbol: 'Po', position: { x: 17, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Polonium' },
    { symbol: 'At', position: { x: 18, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Astat' },
    { symbol: 'Rn', position: { x: 19, y: 6 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Radon' },
    { symbol: 'Rf', position: { x: 5, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Rutherfordium' },
    { symbol: 'Db', position: { x: 6, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Dubnium' },
    { symbol: 'Sg', position: { x: 7, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Seaborgium' },
    { symbol: 'Bh', position: { x: 8, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Bohrium' },
    { symbol: 'Hs', position: { x: 9, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Hassium' },
    { symbol: 'Mt', position: { x: 10, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Meitnerium' },
    { symbol: 'Ds', position: { x: 11, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/esrmstadtium' },
    { symbol: 'Rg', position: { x: 12, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/R%C3%B8ntgenium' },
    { symbol: 'Cn', position: { x: 13, y: 7 }, category: 'blue', url: 'https://es.wikipedia.org/wiki/Copernicium' },
    { symbol: 'Nh', position: { x: 14, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Nihonium' },
    { symbol: 'Fl', position: { x: 15, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Flerovium' },
    { symbol: 'Mc', position: { x: 16, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Moscovium' },
    { symbol: 'Lv', position: { x: 17, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Livermorium' },
    { symbol: 'Ts', position: { x: 18, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Tennessin' },
    { symbol: 'Og', position: { x: 19, y: 7 }, category: 'purple', url: 'https://es.wikipedia.org/wiki/Oganesson' },
    ];
  
    const periodicTable = document.querySelector('.periodic-table')
  
    elements.forEach((element) => {
        const button = document.createElement('button');
        button.classList.add('element', element.category);  // Add category class
        button.textContent = element.symbol;
        button.style.gridColumn = element.position.x;
        button.style.gridRow = element.position.y;
        periodicTable.appendChild(button);
        button.style.fontFamily = "Minecraft";
        button.addEventListener("click", () =>{location.href=element.url;} );
      }); 
  });
